### ISSUE TITLE
Attention timer not updating with ball of wool

### ISSUE THREAD

**Issue by capSAR273** [pieterjanbuntinx/kitten-tracker#14]
For the "Needs Attention", the timer does not update if I use a ball of wool on the cat. Stroking the kitten correctly updates the timer though. Thank you for the time format change though! Very nice to save screen space.

I'm on version bca0d078

**Comment by nicholaswen** [comment]
I think it's due to a typo [here](https://github.com/pieterjanbuntinx/kitten-tracker/blob/master/src/main/java/com/kittentracker/KittenPlugin.java#L67) in `DIALOG_CAT_BALL_OF_WOOL`. There should be a space between it and is.

Current: "That kitten loves to play with that ball of wool. I think itis its favourite."
Fixed: "That kitten loves to play with that ball of wool. I think it is its favourite."
